### ISSUE TITLE
How to browserify only certain helpers or categories

### ISSUE THREAD

**Issue by markcarey** [doowb/handlebars-helpers-browserify-example#1]
I used the method described in their example and ended up with a 2.3MB .js file that needs to be loaded by the browser.  Obviously a non-starter.  I know that I could minify that to reduce the size, but is there a way to only build a subset of helpers?

**Comment by doowb** [comment]
You can require in a collection directly by doing `var arrayHelpers = require('handlebars-helpers/lib/array.js')`. Some of the common pieces of code will still be loaded, but this will reduce the size and when used with minify it'll even be better.
